### ISSUE TITLE
Low vector math support

### ISSUE THREAD

**Issue by darren-moore** [ianw3214/WyvernsNest#3]
The [current vector struct](https://github.com/ianw3214/WyvernsNest/blob/master/src/math/vec.hpp) isn't too flexible. I propose one of the following:
1. Utilize an external vector math library like GLM or Eigen.
2. Expand the current implementation with(for a start):
    * Vector addition
    * Scalar multiplication
    * Normalization
    * Dot products

**Comment by ianw3214** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Expand vector struct functionalities](https://trello.com/c/Mef88qHE/23-expand-vector-struct-functionalities)
